package com.carolinasanchez;

public class Car {
    private String make;
    private String model;
    private int mileage;
    private float gasTankPercent;

    public Car(String make, String model, int mileage, float gasTankPercent) {
        this.make = make;
        this.model = model;
        this.mileage = mileage;
        this.gasTankPercent = gasTankPercent;
    }

    public String getMake() {
        return make;
    }

    public void setMake(String make) {
        this.make = make;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public int getMileage() {
        return mileage;
    }

    public void setMileage(int mileage) {
        this.mileage = mileage;
    }

    public float getGasTankPercent() {
        return gasTankPercent;
    }

    public void setGasTankPercent(float gasTankPercent) {
        this.gasTankPercent = gasTankPercent;
    }

    @Override // Can be auto generated by selecting Override/Implement methods once you type in @. Then you can add what you want the string to say.
    public String toString() {
        return "This is a " + this.make + " model " + this.model + " with " + this.mileage + " miles and a " + this.gasTankPercent + "% gas tank percentage.";
    }
}